# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/centos7"
  config.vm.network "private_network", ip: "192.168.56.20"
  config.vm.network "public_network"
  config.vm.provision "shell", path: "provision.sh" 
   config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
     vb.gui = false
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "1024"
   end
  
end
