Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.hostname = "node01.local.lab"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "private_network", ip: "192.168.56.3"
  config.vm.provision "shell", path: "provision.sh"
  
  VAGRANT_COMMAND = ARGV[0]
    if VAGRANT_COMMAND == "ssh"
      config.ssh.username = 'devops'
  end

end