Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.hostname = "ansible.local.lab"
# config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "private_network", ip: "192.168.56.2"

end