# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.network "private_network", ip: "192.168.56.21"
  config.vm.network "public_network"
  config.vm.provision "shell", path: "provision.sh" 

  
end
